# Generated by Django 3.2.7 on 2021-12-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooster_name', models.CharField(max_length=256)),
                ('periode1', models.TimeField()),
                ('periode2', models.TimeField()),
                ('periode3', models.TimeField()),
                ('periode4', models.TimeField()),
                ('pouse1', models.TimeField()),
                ('periode5', models.TimeField()),
                ('periode6', models.TimeField()),
                ('periode7', models.TimeField()),
                ('periode8', models.TimeField()),
                ('pouse2', models.TimeField()),
                ('periode9', models.TimeField()),
                ('periode10', models.TimeField()),
                ('periode11', models.TimeField()),
                ('periode12', models.TimeField()),
            ],
        ),
    ]
