# Generated by Django 3.2.7 on 2021-12-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KlokRooster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooster',
            name='uitkomtyd',
            field=models.TimeField(default='14:00'),
        ),
    ]
