# Generated by Django 3.2.7 on 2021-12-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KlokRooster', '0002_rooster_uitkomtyd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooster',
            name='uitkomtyd',
            field=models.TimeField(),
        ),
    ]
