# Generated by Django 3.2.7 on 2021-12-09 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KlokRooster', '0003_alter_rooster_uitkomtyd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooster',
            old_name='rooster_name',
            new_name='name',
        ),
    ]
