# Generated by Django 3.2.7 on 2021-12-10 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KlokRooster', '0005_rename_name_rooster_naam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooster',
            name='naam',
            field=models.CharField(default='Nuwe Rooster', max_length=256),
        ),
        migrations.AlterField(
            model_name='rooster',
            name='periode1',
            field=models.TimeField(default='7:30'),
        ),
        migrations.AlterField(
            model_name='rooster',
            name='periode10',
            field=models.TimeField(default='12:30'),
        ),
        migrations.AlterField(
            model_name='rooster',
            name='periode11',
            field=models.TimeField(default='13:00'),
        ),
        migrations.AlterField(
            model_name='rooster',
            name='periode12',
            field=models.TimeField(default='13:30'),
        ),
        migrations.AlterField(
            model_name='rooster',
            name='periode2',
            field=models.TimeField(default='8:00'),
        ),
        migrations.AlterField(
            model_name='rooster',
            name='periode3',
            field=models.TimeField(default='8:30'),
        ),
        migrations.AlterField(
            model_name='rooster',
            name='periode4',
            field=models.TimeField(default='9:00'),
        ),
        migrations.AlterField(
            model_name='rooster',
            name='periode5',
            field=models.TimeField(default='9:45'),
        ),
        migrations.AlterField(
            model_name='rooster',
            name='periode6',
            field=models.TimeField(default='10:15'),
        ),
        migrations.AlterField(
            model_name='rooster',
            name='periode7',
            field=models.TimeField(default='10:45'),
        ),
        migrations.AlterField(
            model_name='rooster',
            name='periode8',
            field=models.TimeField(default='11:15'),
        ),
        migrations.AlterField(
            model_name='rooster',
            name='periode9',
            field=models.TimeField(default='12:00'),
        ),
        migrations.AlterField(
            model_name='rooster',
            name='pouse1',
            field=models.TimeField(default='9:30'),
        ),
        migrations.AlterField(
            model_name='rooster',
            name='pouse2',
            field=models.TimeField(default='11:45'),
        ),
        migrations.AlterField(
            model_name='rooster',
            name='uitkomtyd',
            field=models.TimeField(default='14:00'),
        ),
    ]
