# Generated by Django 3.2.7 on 2021-12-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KlokRooster', '0006_auto_20211210_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooster',
            name='luisterend',
            field=models.BooleanField(default=False),
        ),
    ]
