# Generated by Django 4.0.1 on 2022-01-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KlokRooster', '0007_rooster_luisterend'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooster',
            name='aantreetyd',
            field=models.TimeField(default='7:25'),
        ),
    ]
