# Generated by Django 4.0.1 on 2022-01-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KlokRooster', '0008_rooster_aantreetyd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooster',
            name='aantreetyd',
            field=models.TimeField(default='7:20'),
        ),
    ]
